sudo: required
language : generic
services:
    -docker


before_install:
    - docker build -t atisha/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true atisha/react-test npm test 

after_success:
    - docker build -t atisha/multi-client ./client
    - docker build -t atisha/multi-nginx  ./nginx
    - docker build -t atisha/multi-server ./server
    - docker build -t atisha/multi-worker ./worker
    #login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take images and push them to docker hub
    - docker push atisha/multi-client
    - docker push atisha/multi-nginx
    - docker push atisha/multi-server
    - docker push atisha/multi-worker